image: demoshang/docker-bash:18

services:
  - docker:dind

variables:
  DOCSET_NAME: rxjs6.docset
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH

stages:
  - build
  - github_release


build:
  stage: build
  artifacts:
    # 保存压缩包的名称
    name: "${CI_COMMIT_SHA}-${DOCSET_NAME}"
    # 要保存的文件的路径
    paths:
      - ${DOCSET_NAME}/
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - apk add jq
    # docker build
    - bash devops/local/index.sh docker

github_release:
  stage: github_release
  variables:
    GITHUB_RELEASE_VERSION: v0.7.2
    GITHUB_REPO: dash-rxjs-6
    # 要压缩上传的路径
    GITHUB_UPLOAD_PATH: ${DOCSET_NAME}
    # 压缩后的名称
    GITHUB_UPLOAD_ZIP_NAME: ${DOCSET_NAME}.zip
  script:
    - apk add --no-cache jq wget openssl tar zip
    - bash devops/local/index.sh release
  only:
    - tags
